### ISSUE TITLE
Function  lsm303agr_read_reg should set MSB in the address of register?

### ISSUE THREAD

**Issue by wzab** [STMicroelectronics/lsm303agr-pid#1]
I tried to use the LSM303AGR accelerometer on a STM32F411E-DISCO board. However the function lsm303agr_acceleration_raw_get returned the 6 times the same byte.
I have implemented the platform dependent read function with HAL_I2C_Mem_Read. Trying to find the source of the problem, I've read in the datasheet:

    The I2C embedded inside the LSM303AGR behaves like a slave device and the following
    protocol must be adhered to. After the start condition (ST) a slave address is sent, once a
    slave acknowledge (SAK) has been returned, an 8-bit subaddress (SUB) is transmitted: the
    7 LSb represent the actual register address while the MSB enables address auto increment.
    If the MSb of the SUB field is 1, the SUB (register address) is automatically increased to
    allow multiple data read/writes.
    (page 38 in https://www.st.com/resource/en/datasheet/lsm303agr.pdf )

 I modified the function  lsm303agr_read_reg by setting the MSB in the register address:

```
int32_t lsm303agr_read_reg(stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
{
   int32_t ret;
   ret = ctx->read_reg(ctx->handle, reg | 0x80, data, len);
   return ret;
}
```
With that modification, the accelerometer is read correctly.

**Comment by avisconti** [comment]
> I tried to use the LSM303AGR accelerometer on a STM32F411E-DISCO board. However the function lsm303agr_acceleration_raw_get returned the 6 times the same byte. I have implemented the platform dependent read function with HAL_I2C_Mem_Read. Trying to find the source of the problem, I've read in the datasheet:
> 
> ```
> The I2C embedded inside the LSM303AGR behaves like a slave device and the following
> protocol must be adhered to. After the start condition (ST) a slave address is sent, once a
> slave acknowledge (SAK) has been returned, an 8-bit subaddress (SUB) is transmitted: the
> 7 LSb represent the actual register address while the MSB enables address auto increment.
> If the MSb of the SUB field is 1, the SUB (register address) is automatically increased to
> allow multiple data read/writes.
> (page 38 in https://www.st.com/resource/en/datasheet/lsm303agr.pdf )
> ```
> 
> I modified the function lsm303agr_read_reg by setting the MSB in the register address:
> 
> ```
> int32_t lsm303agr_read_reg(stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
> {
>    int32_t ret;
>    ret = ctx->read_reg(ctx->handle, reg | 0x80, data, len);
>    return ret;
> }
> ```
> 
> With that modification, the accelerometer is read correctly.

Whatever you said concerning the "| 0x80" to enable auto-increment is correct, but you don't need to change the driver read routine, which is already calling a platform dependent "ctx->read_reg" routine.

In fact you can take a look to the driver example here:
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm303agr_STdC/examples/lsm303agr_read_data_polling.c#L335

P.S.
I'm by the way re-consdering what I wrote above, because the auto-increment stuff belongs more to the driver rather than platform specific stuff. So, I'll think more about it

**Comment by wzab** [comment]
Yes, I was using the reference you have referenced (and modifying it for my needs).
Setting the MSB to increment the address is chip-specific so I think it should be in the driver for that particular chip.
BTW, I'm surprised that no one has discovered that problem earlier. Does it happen only when somebody uses HAL_I2C_Mem_Read (not HAL_I2C_Mem_Read_DMA or HAL_I2C_Mem_Read_IT)?
Why HAL_I2C_Mem_Write does work? 
Is setting the MSB needed only in case if STOP condition happens between sending the address and reading the data?
(Then in case of Write the problem does not exist as everything goes in a single multibyte write transaction.)
In fact it would be good if HAL_I2C_Mem_Read supported the REPEATED START between sending the memory address and reading the data.

**Comment by avisconti** [comment]
> Yes, I was using the reference you have referenced (and modifying it for my needs). Setting the MSB to increment the address is chip-specific so I think it should be in the driver for that particular chip. BTW, I'm surprised that no one has discovered that problem earlier. Does it happen only when somebody uses HAL_I2C_Mem_Read (not HAL_I2C_Mem_Read_DMA or HAL_I2C_Mem_Read_IT)? Why HAL_I2C_Mem_Write does work? Is setting the MSB needed only in case if STOP condition happens between sending the address and reading the data? (Then in case of Write the problem does not exist as everything goes in a single multibyte write transaction.) In fact it would be good if HAL_I2C_Mem_Read supported the REPEATED START between sending the memory address and reading the data.
                                                                                 
Sorry for late reply.                                                                                 
I'm not sure what is the behaviour of HAL_I2C_Mem_Read/HAL_I2C_Mem_Write. I know that you have to explicity set the MSB (for this sensor) to request auto incrementing of address. But it is sensor specific, not HAL specific.                                                                                 
                                                                                 
Coming back to your point I changed my mind, and I think it is better to keep the setting of auto-increment in the platform part. This because for I2C you have to do reg | 0x80, but for SPI reg | 0x40. Take a look to the examples:                                                                                 
                                                                                 
```
static int32_t platform_read(void *handle, uint8_t reg, uint8_t *bufp,              
                             uint16_t len)                                          
{                                                                                   
  sensbus_t *sensbus = (sensbus_t *)handle;                                         
#if defined(NUCLEO_F411RE)                                                          
                                                                                    
  if (sensbus->i2c_address == LSM303AGR_I2C_ADD_XL) {                               
    /* enable auto incremented in multiple read/write commands */                   
    reg |= 0x80;                                                                    
  }                                                                                 
                                                                                    
  HAL_I2C_Mem_Read(sensbus->hbus, sensbus->i2c_address, reg,                        
                   I2C_MEMADD_SIZE_8BIT, bufp, len, 1000);                          
#elif defined(STEVAL_MKI109V3)                                                      
  reg |= 0x80;                                                                      
                                                                                    
  if (sensbus->cs_pin == CS_up_Pin) {                                               
    /* enable auto incremented in multiple read/write commands */                   
    reg |= 0x40;                                                                    
  }                                                                                 
                                                                                    
  HAL_GPIO_WritePin(sensbus->cs_port, sensbus->cs_pin, GPIO_PIN_RESET);             
  HAL_SPI_Transmit(sensbus->hbus, &reg, 1, 1000);                                   
  HAL_SPI_Receive(sensbus->hbus, bufp, len, 1000);                                  
  HAL_GPIO_WritePin(sensbus->cs_port, sensbus->cs_pin, GPIO_PIN_SET);               
#elif defined(SPC584B_DIS)                                                          
                                                                                    
  if (sensbus->i2c_address == LSM303AGR_I2C_ADD_XL) {                               
    /* enable auto incremented in multiple read/write commands */                   
    reg |= 0x80;                                                                    
  }                                                                                 
                                                                                    
  i2c_lld_read(sensbus->hbus, sensbus->i2c_address & 0xFE, reg, bufp,               
               len);                                                                                                                                            
#endif                                                                          
  return 0;                                                                     
}                     
```                                                          
I suggest you follow same approach just to avoid issues if you change bus.

**Comment by avisconti** [comment]
I'm closing this issue. If you don't feel the case it's closed you may re-open it with comments.
